spring:
  application:
    name: springboot-order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: mysql:///test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    allow-redirects: true
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8088/eureka/
  instance:
        prefer-ip-address: true
server:
  port: 8085
